### PR TITLE
Add prelude so you don't have to import every single feature every single time, and update the examples to use the prelude

### PR DESCRIPTION
**Pull request by Aztro-dev**
Also changed the `.gitignore` to include (ignore) all `.DS_Store` files. The extra commits are because of an oopsie

### CODE REVIEW

**Comment by VirgileHenry** [comment]
I've seen that some rust libs use preludes, but isn't this deporting the issue from `use nerf::[...];` to `use nerf::prelude::[...]`, being the same thing in the end ?

**Comment by Aztro-dev** [comment]
Not really, the idea of a prelude is to use stuff that is kind of barebones (the stuff that you would import into a file every single time). You can modify the prelude to have less things (which I haven't done, as I don't feel I have enough experience in the codebase), which is the idea of a prelude.

**Comment by Aztro-dev** [comment]
You also (pretty much) never import individual things from the prelude. You import everything from the prelude and then you can use it in your project.

**Comment by VirgileHenry** [comment]
Thanks for the info! 
With rhe current state of the lib, and the prelude being an import of the lib like before, I don't think this is worth it for now.
However, there are high chances I'll reconsider adding a prelude when the library will grow and I'll add more widgets that will not need to be included by default.

**Pull request closed without merging**
